export const products = [
  {
    id: 1,
    name: "Trek Marlin 7",
    type: "mountain",
    brand: "Trek",
    price: 1299,
    oldPrice: 1499,
    image: "veloshop/assets/images/mountain-ridge.svg",
    wheelSize: 29,
    frame: "Алюминий",
    brakes: "Гидравлические дисковые",
    purpose: "Трейл и город",
    rating: 4.8,
    isPopular: true,
    isPromo: true,
    shortSpecs: ['29"', "Алюминий", "Дисковые тормоза"]
  },
  {
    id: 2,
    name: "Giant Talon E+",
    type: "electric",
    brand: "Giant",
    price: 2499,
    oldPrice: 2799,
    image: "veloshop/assets/images/electric-drive.svg",
    wheelSize: 29,
    frame: "Алюминий",
    brakes: "Гидравлические дисковые",
    purpose: "Город и смешанные маршруты",
    rating: 4.9,
    isPopular: true,
    isPromo: false,
    shortSpecs: ['29"', "Средний мотор", "625 Wh"]
  },
  {
    id: 3,
    name: "Scott Speedster 30",
    type: "road",
    brand: "Scott",
    price: 1899,
    oldPrice: 2099,
    image: "veloshop/assets/images/road-sprint.svg",
    wheelSize: 28,
    frame: "Алюминиевый сплав",
    brakes: "Механические дисковые",
    purpose: "Фитнес и длинные маршруты",
    rating: 4.7,
    isPopular: true,
    isPromo: false,
    shortSpecs: ['28"', "Алюминий", "Шоссейная геометрия"]
  },
  {
    id: 4,
    name: "Merida Crossway 100",
    type: "city",
    brand: "Merida",
    price: 899,
    oldPrice: 999,
    image: "veloshop/assets/images/city-glide.svg",
    wheelSize: 28,
    frame: "Алюминий",
    brakes: "Гидравлические дисковые",
    purpose: "Ежедневные поездки по городу",
    rating: 4.6,
    isPopular: false,
    isPromo: true,
    shortSpecs: ['28"', "Комфортная посадка", "Городская настройка"]
  },
  {
    id: 5,
    name: "GT Performer Pro",
    type: "bmx",
    brand: "GT",
    price: 649,
    oldPrice: 749,
    image: "veloshop/assets/images/bmx-spark.svg",
    wheelSize: 20,
    frame: "Хромомолибден",
    brakes: "U-brake",
    purpose: "Парк и стрит-трюки",
    rating: 4.5,
    isPopular: true,
    isPromo: false,
    shortSpecs: ['20"', "Хромомолибден", "Стрит-сборка"]
  },
  {
    id: 6,
    name: "Cube Aim Race",
    type: "mountain",
    brand: "Cube",
    price: 1099,
    oldPrice: 1199,
    image: "veloshop/assets/images/mountain-ridge.svg",
    wheelSize: 29,
    frame: "Алюминий Lite",
    brakes: "Гидравлические дисковые",
    purpose: "Трейлы выходного дня",
    rating: 4.7,
    isPopular: false,
    isPromo: false,
    shortSpecs: ['29"', "Вилка 100 мм", "Трансмиссия 1x"]
  },
  {
    id: 7,
    name: "Cannondale Quick 3",
    type: "city",
    brand: "Cannondale",
    price: 1199,
    oldPrice: 0,
    image: "veloshop/assets/images/city-glide.svg",
    wheelSize: 28,
    frame: "SmartForm C3",
    brakes: "Гидравлические дисковые",
    purpose: "Быстрые городские поездки",
    rating: 4.8,
    isPopular: true,
    isPromo: false,
    shortSpecs: ['28"', "Городской фитнес", "Лёгкая рама"]
  },
  {
    id: 8,
    name: "Specialized Allez",
    type: "road",
    brand: "Specialized",
    price: 1599,
    oldPrice: 1749,
    image: "veloshop/assets/images/road-sprint.svg",
    wheelSize: 28,
    frame: "E5 Alloy",
    brakes: "Механические дисковые",
    purpose: "Тренировки и скорость",
    rating: 4.7,
    isPopular: true,
    isPromo: true,
    shortSpecs: ['28"', "Скоростная посадка", "Карбоновая вилка"]
  },
  {
    id: 9,
    name: "Haibike AllTrack 5",
    type: "electric",
    brand: "Haibike",
    price: 2799,
    oldPrice: 3099,
    image: "veloshop/assets/images/electric-drive.svg",
    wheelSize: 29,
    frame: "Алюминий",
    brakes: "Гидравлические дисковые",
    purpose: "Дальние приключенческие поездки",
    rating: 4.9,
    isPopular: false,
    isPromo: true,
    shortSpecs: ['29"', "Мотор Bosch", "Готов к трейлу"]
  },
  {
    id: 10,
    name: "Haro Downtown DLX",
    type: "bmx",
    brand: "Haro",
    price: 479,
    oldPrice: 0,
    image: "veloshop/assets/images/bmx-spark.svg",
    wheelSize: 20,
    frame: "Hi-Ten сталь",
    brakes: "U-brake",
    purpose: "База для стрита",
    rating: 4.3,
    isPopular: false,
    isPromo: false,
    shortSpecs: ['20"', "Сталь", "Стартовая сборка"]
  },
  {
    id: 11,
    name: "Norco Storm 4",
    type: "mountain",
    brand: "Norco",
    price: 799,
    oldPrice: 899,
    image: "veloshop/assets/images/mountain-ridge.svg",
    wheelSize: 27.5,
    frame: "Алюминий",
    brakes: "Механические дисковые",
    purpose: "Стартовые трейловые поездки",
    rating: 4.4,
    isPopular: false,
    isPromo: false,
    shortSpecs: ['27.5"', "Вход в трейл", "Универсальный"]
  },
  {
    id: 12,
    name: "Orbea Vector 20",
    type: "city",
    brand: "Orbea",
    price: 999,
    oldPrice: 1099,
    image: "veloshop/assets/images/city-glide.svg",
    wheelSize: 28,
    frame: "Urban alloy",
    brakes: "Гидравлические дисковые",
    purpose: "Комфортные ежедневные поездки",
    rating: 4.6,
    isPopular: true,
    isPromo: false,
    shortSpecs: ['28"', "Вертикальная посадка", "Городской комфорт"]
  }
];

export const typeOptions = [
  { value: "all", label: "All bikes" },
  { value: "mountain", label: "Mountain" },
  { value: "road", label: "Road" },
  { value: "city", label: "City" },
  { value: "bmx", label: "BMX" },
  { value: "electric", label: "Electric" }
];
